[tool.pylint."messages control"]
disable = [
    "pointless-string-statement",
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring",
    "attribute-defined-outside-init"
]